// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: connection_router.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConnectionRouter_SendDataToPropagationManager_FullMethodName = "/gosphere.ConnectionRouter/SendDataToPropagationManager"
)

// ConnectionRouterClient is the client API for ConnectionRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionRouterClient interface {
	SendDataToPropagationManager(ctx context.Context, in *BlockData, opts ...grpc.CallOption) (*Response, error)
}

type connectionRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionRouterClient(cc grpc.ClientConnInterface) ConnectionRouterClient {
	return &connectionRouterClient{cc}
}

func (c *connectionRouterClient) SendDataToPropagationManager(ctx context.Context, in *BlockData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, ConnectionRouter_SendDataToPropagationManager_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionRouterServer is the server API for ConnectionRouter service.
// All implementations should embed UnimplementedConnectionRouterServer
// for forward compatibility
type ConnectionRouterServer interface {
	SendDataToPropagationManager(context.Context, *BlockData) (*Response, error)
}

// UnimplementedConnectionRouterServer should be embedded to have forward compatible implementations.
type UnimplementedConnectionRouterServer struct {
}

func (UnimplementedConnectionRouterServer) SendDataToPropagationManager(context.Context, *BlockData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataToPropagationManager not implemented")
}

// UnsafeConnectionRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionRouterServer will
// result in compilation errors.
type UnsafeConnectionRouterServer interface {
	mustEmbedUnimplementedConnectionRouterServer()
}

func RegisterConnectionRouterServer(s grpc.ServiceRegistrar, srv ConnectionRouterServer) {
	s.RegisterService(&ConnectionRouter_ServiceDesc, srv)
}

func _ConnectionRouter_SendDataToPropagationManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionRouterServer).SendDataToPropagationManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionRouter_SendDataToPropagationManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionRouterServer).SendDataToPropagationManager(ctx, req.(*BlockData))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionRouter_ServiceDesc is the grpc.ServiceDesc for ConnectionRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gosphere.ConnectionRouter",
	HandlerType: (*ConnectionRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDataToPropagationManager",
			Handler:    _ConnectionRouter_SendDataToPropagationManager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection_router.proto",
}
